# Build Settings
markdown: kramdown
theme: minima
minima:
  skin: dark
plugins:
  - jekyll-remote-theme
title: Workshop on Data Science for  Justice Delivery in India  (DSJDI-2022) 
# subtitle: (in conjunction with Tenth International Conference on Big  Data Analytics 2022 (BDA 2022), 19 - 22, December 2022, http://wwwbda2022.org)
